### PR TITLE
Fix/handling-offline-access

### PR DESCRIPTION
**Pull request by d-mashchenko**

### CODE REVIEW

**Review by a-nahaitsev — CHANGES_REQUESTED** [review]
maybe we should handle fetching events to not see errors in console
image

**Review by o-mehlii — COMMENTED** [review]
If the Internet connection is lost, the application disconnects from Trello.
image

**Comment by a-nahaitsev** [comment]
you may add checking online in this function
`  const getTrelloCards = async () => {
    try {
      const trelloCards = await global.ipcRenderer.invoke(
        "trello:get-cards",
        trelloUser.accessToken
      );

      const newTrelloTasks = trelloCards.map((card) =>
        replaceHyphensWithSpaces(`TT:: ${card.name} ${card.shortUrl}`)
      );

      setTrelloTasks(newTrelloTasks);
    } catch (error) {
      const online = await isOnline();

      if (!online) {
        localStorage.removeItem("trello-user");
      }
      setTrelloTasks([]);
    }
  };`
  
  or in useEffect
  `  useEffect(() => {
    (async () => {
      const online = await isOnline();

      if (trelloUser && online) await getTrelloCards();
    })();
  }, []);`

**Comment by d-mashchenko** [comment]
> maybe we should handle fetching events to not see errors in console image

since we no longer have Google message in our section, I think it will be easier to handle this case after merging your big PR, the same goes for everything else. Now we check only integration button and links in "waht's new" section. So i checked all requests one more time after merging all PR for our release.

**Review by a-nahaitsev — APPROVED** [review]

**Pull request merged**
